
#Charger MODUS main Configuration -----------------------------------------
#--------------------------------------------------------------------------
hmi.language=de
acType=AC22
chargerModus=3
multipleCharging=true
#AcOutlets requires system restart
ACOutlets=1
#ccsCharger requires system restart
ccsCharger=true
#chademoCharger requires system restart
chademoCharger=true
#stationId requires system restart
stationId=EFACECQC0005

#Client specific Options------------------------------------------------------
#--------------------------------------------------------------------------
eTerminalCommEnabled=true
uiInterface=OCPP15
centralManagementEndpointRWE=http://10.0.0.179:9000/QC45


#Communication Protocol Configuration -------------------------------------
#--------------------------------------------------------------------------
#centralManagementEnabled enables the communication with Central System
centralmanagement.enabled=true
#Central System endpoint 
centralmanagement.endpoint=http://10.0.0.179:9000/QC45
#Communication Protocol used
communicationProtocol=OCPP15
#Always send Authorization message to Central System ignoring whitelist
OCPP.checkCard.online=true
#interval of time to send heartbeat messages
heartBeatInterval=60
#allow a charge in case of communication lost
allowOfflineCharging=false
#Central System communication timeout
connection.timeout=20
#interval of time to send meter values during charge
meterValue.sampleInterval=30



#Factory Settings ----------------------------------------------------
#--------------------------------------------------------------------------
serialNumber=TEST_CHARGER2
model=NA
outOfService=false
#max time in charge: seconds
charging.maxtime=14400
#max time in use without starting a charge: minutes
inuse.maxtime=5
#max Time In Charge with No Energy detected: minutes
charging.noenergy.maxtime=5
#maxTimeAfterCharge ???
charging.after.maxtime=60
#enable load balance
load.balance.enabled=false
#max power
maxPower=120 
